apiVersion: apps/v1
kind: Deployment
metadata:
  name: repo
  namespace: flomesh
  labels:
    app.kubernetes.io/instance: repo
    app.kubernetes.io/component: repo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: repo
      app.kubernetes.io/component: repo
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: repo
        app.kubernetes.io/component: repo
    spec:
      containers:
      - name: repo
        image: flomesh/pipy:0.30.0-100
        imagePullPolicy: IfNotPresent
        command:
        - sh
        - -c
        - |+
          /usr/local/bin/pipy --admin-port=6060
        ports:
        - name: repo
          containerPort: 6060
        resources:
          limits:
            cpu: 1000m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 20M
        livenessProbe:
          tcpSocket:
            port: 6060
          periodSeconds: 20
        readinessProbe:
          tcpSocket:
            port: 6060
          periodSeconds: 20
        startupProbe:
          tcpSocket:
            port: 6060
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 10
      serviceAccountName: traffic-guru
      terminationGracePeriodSeconds: 30