apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fsm.configmaps.jobs.name }}
  namespace: {{ include "fsm.namespace" . }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
data:
  cluster_local.yaml: |-
{{ (.Files.Get "components/cluster_local.yaml") | indent 4 }}
  default_proxyprofile.yaml: |-
{{ (.Files.Get "components/default_proxyprofile.yaml") | indent 4 }}
