apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fsm-leader-election-rolebinding
  namespace: {{ .Values.fsm.leaderElection.namespace }}
  labels:
    {{- include "fsm.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fsm-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "fsm.serviceAccountName" . }}
  namespace: {{ include "fsm.namespace" . }}